### ISSUE TITLE
How to distinguish between write and read

### ISSUE THREAD

**Issue by kemoantemo** [jonasstrehle/supercookie#22]
I saw the documentation but didn't really get it how can you know if this is the first time for the user to enter the site so you car write some favicon to him and give him identifier or if he already have favicons and u will then give him 404 request on all favicons. so can you please tell in details how the script distinguish? Or maybe the first redirect is always test and if the user asked for favicon "a" then he is new and if not we start reading?

**Comment by jonasstrehle** [comment]
**Short explanation**: Distinction between Read and Write is also made via the initial favicon on the start page.
So the first step is to check whether the favicon for the base domain is requested when the browser visits the page. If that favicon is requested, then this should be the user’s first visit and we continue in write mode. Otherwise we assume that the identifier has already been written and we switch to read mode.

**Comment by kemoantemo** [comment]
@jonasstrehle ty very much ♥️
